.PHONY: test check tidy run

test:
	go test ./...
	go test ./pkg/ai/provider/anthropic/...
	go test ./pkg/ai/provider/openai/...
	go test ./pkg/ai/provider/openairesponses/...
	go test ./pkg/ai/provider/google/...
	go test ./pkg/ai/provider/geminicli/...

check:
	go vet ./...
	go vet ./pkg/ai/provider/anthropic/...
	go vet ./pkg/ai/provider/openai/...
	go vet ./pkg/ai/provider/openairesponses/...
	go vet ./pkg/ai/provider/google/...
	go vet ./pkg/ai/provider/geminicli/...
	gofmt -l .

run:
	go run github.com/sonnes/pi-go/cmd/pi $(ARGS)

tidy:
	go mod tidy
	cd cmd/pi && go mod tidy
	cd pkg/ai/provider/anthropic && go mod tidy
	cd pkg/ai/provider/openai && go mod tidy
	cd pkg/ai/provider/openairesponses && go mod tidy
	cd pkg/ai/provider/google && go mod tidy
	cd pkg/ai/provider/geminicli && go mod tidy
