.PHONY: test check tidy

test:
	go test ./...
	go test ./pkg/ai/provider/anthropic/...
	go test ./pkg/ai/provider/openai/...
	go test ./pkg/ai/provider/google/...

check:
	go vet ./...
	go vet ./pkg/ai/provider/anthropic/...
	go vet ./pkg/ai/provider/openai/...
	go vet ./pkg/ai/provider/google/...
	gofmt -l .

tidy:
	go mod tidy
	cd pkg/ai/provider/anthropic && go mod tidy
	cd pkg/ai/provider/openai && go mod tidy
	cd pkg/ai/provider/google && go mod tidy
