// Command genmodels generates per-provider models.go files from the
// models.dev catalog (https://models.dev/api.json).
//
// Run it with `make gen` (or `go run ./internal/genmodels`). It fetches
// the catalog, keeps text-generation models, and writes one var per model
// plus Models() and LanguageModel() into each target provider package.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode"
)

// target maps a models.dev provider key to a local provider package.
type target struct {
	key string // models.dev top-level provider key
	dir string // path to the provider package, relative to repo root
	pkg string // Go package name
}

var targets = []target{
	{"anthropic", "pkg/ai/provider/anthropic", "anthropic"},
	{"openai", "pkg/ai/provider/openai", "openai"},
	{"openai", "pkg/ai/provider/openairesponses", "openairesponses"},
	{"google", "pkg/ai/provider/google", "google"},
}

// mdModel is the subset of a models.dev model entry we map to ai.Model.
type mdModel struct {
	ID               string `json:"id"`
	Name             string `json:"name"`
	Reasoning        bool   `json:"reasoning"`
	ToolCall         bool   `json:"tool_call"`
	StructuredOutput bool   `json:"structured_output"`
	Temperature      bool   `json:"temperature"`
	Knowledge        string `json:"knowledge"`
	ReleaseDate      string `json:"release_date"`
	LastUpdated      string `json:"last_updated"`
	OpenWeights      bool   `json:"open_weights"`
	Modalities       struct {
		Input  []string `json:"input"`
		Output []string `json:"output"`
	} `json:"modalities"`
	Limit struct {
		Context int `json:"context"`
		Output  int `json:"output"`
	} `json:"limit"`
	Cost struct {
		Input       float64 `json:"input"`
		Output      float64 `json:"output"`
		CacheRead   float64 `json:"cache_read"`
		CacheWrite  float64 `json:"cache_write"`
		Reasoning   float64 `json:"reasoning"`
		InputAudio  float64 `json:"input_audio"`
		OutputAudio float64 `json:"output_audio"`
	} `json:"cost"`
}

type mdProvider struct {
	Models map[string]mdModel `json:"models"`
}

const catalogURL = "https://models.dev/api.json"

func main() {
	input := flag.String("input", "", "path to a models.dev api.json (default: fetch "+catalogURL+")")
	root := flag.String("root", ".", "repo root")
	flag.Parse()

	raw, err := load(*input)
	if err != nil {
		log.Fatalf("genmodels: load catalog: %v", err)
	}

	var catalog map[string]mdProvider
	if err := json.Unmarshal(raw, &catalog); err != nil {
		log.Fatalf("genmodels: parse catalog: %v", err)
	}

	for _, t := range targets {
		prov, ok := catalog[t.key]
		if !ok {
			log.Fatalf("genmodels: provider %q not in catalog", t.key)
		}
		src, n := generate(t.pkg, prov)
		out := filepath.Join(*root, t.dir, "models.go")
		if err := os.WriteFile(out, src, 0o644); err != nil {
			log.Fatalf("genmodels: write %s: %v", out, err)
		}
		fmt.Printf("genmodels: wrote %s (%d models)\n", out, n)
	}
}

func load(path string) ([]byte, error) {
	if path != "" {
		return os.ReadFile(path)
	}
	client := &http.Client{Timeout: 60 * time.Second}
	resp, err := client.Get(catalogURL)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("GET %s: %s", catalogURL, resp.Status)
	}
	return io.ReadAll(resp.Body)
}

// datedID matches a snapshot suffix — a trailing 8-digit date
// (e.g. "-20250805") or "-YYYY-MM-DD" (e.g. "-2024-08-06"). Snapshot
// models are excluded; only the canonical/latest IDs are generated.
var datedID = regexp.MustCompile(`-\d{8}$|\d{4}-\d{2}-\d{2}$`)

// generate returns formatted Go source for a provider package and the
// number of models emitted. Only canonical text-generation models are
// included — dated snapshots are skipped.
func generate(pkg string, prov mdProvider) ([]byte, int) {
	models := make([]mdModel, 0, len(prov.Models))
	for _, m := range prov.Models {
		if !contains(m.Modalities.Output, "text") {
			continue
		}
		if datedID.MatchString(m.ID) {
			continue
		}
		models = append(models, m)
	}
	sort.Slice(models, func(i, j int) bool { return models[i].ID < models[j].ID })

	names := make([]string, len(models))
	seen := map[string]bool{}
	for i, m := range models {
		n := varName(m.ID)
		for seen[n] {
			n += "_"
		}
		seen[n] = true
		names[i] = n
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by internal/genmodels from models.dev. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "import ai %q\n\n", "github.com/sonnes/pi-go/pkg/ai")
	fmt.Fprintf(&b, "// Model-info vars generated from the models.dev catalog. Each is pure\n")
	fmt.Fprintf(&b, "// metadata; bind one with [Provider.LanguageModel] or [ai.NewLanguageModel].\n")
	fmt.Fprintf(&b, "var (\n")
	for i, m := range models {
		fmt.Fprintf(&b, "%s = %s\n", names[i], modelLiteral(m))
	}
	fmt.Fprintf(&b, ")\n\n")

	fmt.Fprintf(&b, "// models is the catalog this provider serves.\n")
	fmt.Fprintf(&b, "var models = []ai.Model{\n")
	for _, n := range names {
		fmt.Fprintf(&b, "%s,\n", n)
	}
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "// Models returns the models served by this provider.\n")
	fmt.Fprintf(&b, "func (p *Provider) Models() []ai.Model {\n")
	fmt.Fprintf(&b, "out := make([]ai.Model, len(models))\n")
	fmt.Fprintf(&b, "copy(out, models)\n")
	fmt.Fprintf(&b, "return out\n}\n\n")

	fmt.Fprintf(&b, "// LanguageModel binds a model-info value to this provider. Sugar for\n")
	fmt.Fprintf(&b, "// [ai.NewLanguageModel].\n")
	fmt.Fprintf(&b, "func (p *Provider) LanguageModel(info ai.Model) ai.LanguageModel {\n")
	fmt.Fprintf(&b, "return ai.NewLanguageModel(info, p)\n}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		log.Fatalf("genmodels: format %s: %v\n%s", pkg, err, b.String())
	}
	return src, len(models)
}

func modelLiteral(m mdModel) string {
	var f []string
	f = append(f, fmt.Sprintf("ID: %q", m.ID))
	if m.Name != "" {
		f = append(f, fmt.Sprintf("Name: %q", m.Name))
	}
	if m.Reasoning {
		f = append(f, "Reasoning: true")
	}
	if m.ToolCall {
		f = append(f, "ToolCall: true")
	}
	if m.StructuredOutput {
		f = append(f, "StructuredOutput: true")
	}
	if m.Temperature {
		f = append(f, "Temperature: true")
	}
	if in := modalities(m.Modalities.Input); in != "" {
		f = append(f, "Input: "+in)
	}
	if out := modalities(m.Modalities.Output); out != "" {
		f = append(f, "Output: "+out)
	}
	if m.Limit.Context > 0 || m.Limit.Output > 0 {
		f = append(f, fmt.Sprintf("Limits: ai.Limits{Context: %d, Output: %d}", m.Limit.Context, m.Limit.Output))
		f = append(f, fmt.Sprintf("ContextWindow: %d", m.Limit.Context))
		f = append(f, fmt.Sprintf("MaxTokens: %d", m.Limit.Output))
	}
	if cost := costLiteral(m); cost != "" {
		f = append(f, "Cost: "+cost)
	}
	if m.Knowledge != "" {
		f = append(f, fmt.Sprintf("Knowledge: %q", m.Knowledge))
	}
	if m.ReleaseDate != "" {
		f = append(f, fmt.Sprintf("ReleaseDate: %q", m.ReleaseDate))
	}
	if m.LastUpdated != "" {
		f = append(f, fmt.Sprintf("LastUpdated: %q", m.LastUpdated))
	}
	if m.OpenWeights {
		f = append(f, "OpenWeights: true")
	}
	return "ai.Model{\n" + strings.Join(f, ",\n") + ",\n}"
}

func costLiteral(m mdModel) string {
	c := m.Cost
	var f []string
	add := func(name string, v float64) {
		if v != 0 {
			f = append(f, fmt.Sprintf("%s: %s", name, trimFloat(v)))
		}
	}
	add("Input", c.Input)
	add("Output", c.Output)
	add("CacheRead", c.CacheRead)
	add("CacheWrite", c.CacheWrite)
	add("Reasoning", c.Reasoning)
	add("InputAudio", c.InputAudio)
	add("OutputAudio", c.OutputAudio)
	if len(f) == 0 {
		return ""
	}
	return "ai.Cost{" + strings.Join(f, ", ") + "}"
}

func modalities(ms []string) string {
	var out []string
	for _, m := range ms {
		if c := modalityConst(m); c != "" {
			out = append(out, c)
		}
	}
	if len(out) == 0 {
		return ""
	}
	return "[]ai.Modality{" + strings.Join(out, ", ") + "}"
}

func modalityConst(m string) string {
	switch m {
	case "text":
		return "ai.ModalityText"
	case "image":
		return "ai.ModalityImage"
	case "pdf":
		return "ai.ModalityPDF"
	case "audio":
		return "ai.ModalityAudio"
	case "video":
		return "ai.ModalityVideo"
	default:
		return ""
	}
}

var nonAlnum = regexp.MustCompile(`[^a-zA-Z0-9]+`)

// varName derives an exported Go identifier from a model ID, e.g.
// "claude-sonnet-4-5" -> "ClaudeSonnet45", "gpt-4o" -> "GPT4o".
func varName(id string) string {
	var b strings.Builder
	for _, p := range nonAlnum.Split(id, -1) {
		if p == "" {
			continue
		}
		if strings.EqualFold(p, "gpt") {
			b.WriteString("GPT")
			continue
		}
		r := []rune(p)
		r[0] = unicode.ToUpper(r[0])
		b.WriteString(string(r))
	}
	name := b.String()
	if name == "" {
		name = "M"
	}
	if unicode.IsDigit(rune(name[0])) {
		name = "M" + name
	}
	return name
}

func trimFloat(v float64) string {
	s := fmt.Sprintf("%g", v)
	return s
}

func contains(ss []string, want string) bool {
	for _, s := range ss {
		if s == want {
			return true
		}
	}
	return false
}
