// Code generated by internal/genmodels from models.dev. DO NOT EDIT.

package anthropic

import ai "github.com/sonnes/pi-go/pkg/ai"

// Model-info vars generated from the models.dev catalog. Each is pure
// metadata; bind one with [Provider.LanguageModel] or [ai.NewLanguageModel].
var (
	ClaudeFable5 = ai.Model{
		ID:               "claude-fable-5",
		Name:             "Claude Fable 5",
		Reasoning:        true,
		ToolCall:         true,
		StructuredOutput: true,
		Input:            []ai.Modality{ai.ModalityText, ai.ModalityImage, ai.ModalityPDF},
		Output:           []ai.Modality{ai.ModalityText},
		ContextWindow:    1000000,
		MaxTokens:        128000,
		Cost:             ai.Cost{Input: 10, Output: 50, CacheRead: 1, CacheWrite: 12.5},
		ReleaseDate:      "2026-06-07",
		LastUpdated:      "2026-06-09",
	}
	ClaudeHaiku45 = ai.Model{
		ID:               "claude-haiku-4-5",
		Name:             "Claude Haiku 4.5 (latest)",
		Reasoning:        true,
		ToolCall:         true,
		StructuredOutput: true,
		Temperature:      true,
		Input:            []ai.Modality{ai.ModalityText, ai.ModalityImage, ai.ModalityPDF},
		Output:           []ai.Modality{ai.ModalityText},
		ContextWindow:    200000,
		MaxTokens:        64000,
		Cost:             ai.Cost{Input: 1, Output: 5, CacheRead: 0.1, CacheWrite: 1.25},
		Knowledge:        "2025-02-28",
		ReleaseDate:      "2025-10-15",
		LastUpdated:      "2025-10-15",
	}
	ClaudeOpus41 = ai.Model{
		ID:               "claude-opus-4-1",
		Name:             "Claude Opus 4.1 (latest)",
		Reasoning:        true,
		ToolCall:         true,
		StructuredOutput: true,
		Temperature:      true,
		Input:            []ai.Modality{ai.ModalityText, ai.ModalityImage, ai.ModalityPDF},
		Output:           []ai.Modality{ai.ModalityText},
		ContextWindow:    200000,
		MaxTokens:        32000,
		Cost:             ai.Cost{Input: 15, Output: 75, CacheRead: 1.5, CacheWrite: 18.75},
		Knowledge:        "2025-03-31",
		ReleaseDate:      "2025-08-05",
		LastUpdated:      "2025-08-05",
	}
	ClaudeOpus45 = ai.Model{
		ID:               "claude-opus-4-5",
		Name:             "Claude Opus 4.5 (latest)",
		Reasoning:        true,
		ToolCall:         true,
		StructuredOutput: true,
		Temperature:      true,
		Input:            []ai.Modality{ai.ModalityText, ai.ModalityImage, ai.ModalityPDF},
		Output:           []ai.Modality{ai.ModalityText},
		ContextWindow:    200000,
		MaxTokens:        64000,
		Cost:             ai.Cost{Input: 5, Output: 25, CacheRead: 0.5, CacheWrite: 6.25},
		Knowledge:        "2025-05",
		ReleaseDate:      "2025-11-24",
		LastUpdated:      "2025-11-24",
	}
	ClaudeOpus46 = ai.Model{
		ID:               "claude-opus-4-6",
		Name:             "Claude Opus 4.6",
		Reasoning:        true,
		ToolCall:         true,
		StructuredOutput: true,
		Temperature:      true,
		Input:            []ai.Modality{ai.ModalityText, ai.ModalityImage, ai.ModalityPDF},
		Output:           []ai.Modality{ai.ModalityText},
		ContextWindow:    1000000,
		MaxTokens:        128000,
		Cost:             ai.Cost{Input: 5, Output: 25, CacheRead: 0.5, CacheWrite: 6.25},
		Knowledge:        "2025-05-31",
		ReleaseDate:      "2026-02-04",
		LastUpdated:      "2026-03-13",
	}
	ClaudeOpus47 = ai.Model{
		ID:               "claude-opus-4-7",
		Name:             "Claude Opus 4.7",
		Reasoning:        true,
		ToolCall:         true,
		StructuredOutput: true,
		Input:            []ai.Modality{ai.ModalityText, ai.ModalityImage, ai.ModalityPDF},
		Output:           []ai.Modality{ai.ModalityText},
		ContextWindow:    1000000,
		MaxTokens:        128000,
		Cost:             ai.Cost{Input: 5, Output: 25, CacheRead: 0.5, CacheWrite: 6.25},
		Knowledge:        "2026-01-31",
		ReleaseDate:      "2026-04-14",
		LastUpdated:      "2026-04-16",
	}
	ClaudeOpus48 = ai.Model{
		ID:               "claude-opus-4-8",
		Name:             "Claude Opus 4.8",
		Reasoning:        true,
		ToolCall:         true,
		StructuredOutput: true,
		Input:            []ai.Modality{ai.ModalityText, ai.ModalityImage, ai.ModalityPDF},
		Output:           []ai.Modality{ai.ModalityText},
		ContextWindow:    1000000,
		MaxTokens:        128000,
		Cost:             ai.Cost{Input: 5, Output: 25, CacheRead: 0.5, CacheWrite: 6.25},
		Knowledge:        "2026-01",
		ReleaseDate:      "2026-05-28",
		LastUpdated:      "2026-05-28",
	}
	ClaudeSonnet45 = ai.Model{
		ID:               "claude-sonnet-4-5",
		Name:             "Claude Sonnet 4.5 (latest)",
		Reasoning:        true,
		ToolCall:         true,
		StructuredOutput: true,
		Temperature:      true,
		Input:            []ai.Modality{ai.ModalityText, ai.ModalityImage, ai.ModalityPDF},
		Output:           []ai.Modality{ai.ModalityText},
		ContextWindow:    1000000,
		MaxTokens:        64000,
		Cost:             ai.Cost{Input: 3, Output: 15, CacheRead: 0.3, CacheWrite: 3.75},
		Knowledge:        "2025-07-31",
		ReleaseDate:      "2025-09-29",
		LastUpdated:      "2025-09-29",
	}
	ClaudeSonnet46 = ai.Model{
		ID:               "claude-sonnet-4-6",
		Name:             "Claude Sonnet 4.6",
		Reasoning:        true,
		ToolCall:         true,
		StructuredOutput: true,
		Temperature:      true,
		Input:            []ai.Modality{ai.ModalityText, ai.ModalityImage, ai.ModalityPDF},
		Output:           []ai.Modality{ai.ModalityText},
		ContextWindow:    1000000,
		MaxTokens:        128000,
		Cost:             ai.Cost{Input: 3, Output: 15, CacheRead: 0.3, CacheWrite: 3.75},
		Knowledge:        "2025-08-31",
		ReleaseDate:      "2026-02-17",
		LastUpdated:      "2026-03-13",
	}
	ClaudeSonnet5 = ai.Model{
		ID:               "claude-sonnet-5",
		Name:             "Claude Sonnet 5",
		Reasoning:        true,
		ToolCall:         true,
		StructuredOutput: true,
		Input:            []ai.Modality{ai.ModalityText, ai.ModalityImage, ai.ModalityPDF},
		Output:           []ai.Modality{ai.ModalityText},
		ContextWindow:    1000000,
		MaxTokens:        128000,
		Cost:             ai.Cost{Input: 2, Output: 10, CacheRead: 0.2, CacheWrite: 2.5},
		Knowledge:        "2026-01-31",
		ReleaseDate:      "2026-06-29",
		LastUpdated:      "2026-06-30",
	}
)

// models is the catalog this provider serves.
var models = []ai.Model{
	ClaudeFable5,
	ClaudeHaiku45,
	ClaudeOpus41,
	ClaudeOpus45,
	ClaudeOpus46,
	ClaudeOpus47,
	ClaudeOpus48,
	ClaudeSonnet45,
	ClaudeSonnet46,
	ClaudeSonnet5,
}

// Models returns the models served by this provider.
func (p *Provider) Models() []ai.Model {
	out := make([]ai.Model, len(models))
	copy(out, models)
	return out
}

// LanguageModel binds a model-info value to this provider. Sugar for
// [ai.NewLanguageModel].
func (p *Provider) LanguageModel(info ai.Model) ai.LanguageModel {
	return ai.NewLanguageModel(info, p)
}
